name: basicAuth

services:
  redis:
    image: redis:7
    container_name: auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:17
    container_name: auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth-service:
    build:
      context: .
      dockerfile: auth-module/Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  matching-service:
    build:
      context: .
      dockerfile: matching-module/Dockerfile
    container_name: matching-service
    ports:
      - "8081:8081"
    depends_on:
      auth-service:
        condition: service_started

  task-service:
    build:
      context: .
      dockerfile: task-module/Dockerfile
    container_name: task-service
    ports:
      - "8082:8082"
    depends_on:
      auth-service:
        condition: service_started

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: gateway-service
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_started

volumes:
  postgres-data:
  redis-data:
