server:
  port: 8081

spring:
  application:
    name: matching-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

auth-server:
  url: http://localhost:8080
