FROM eclipse-temurin:21-jdk-jammy AS build
WORKDIR /app

COPY gradlew ./
COPY gradle ./gradle
COPY settings.gradle.kts build.gradle.kts ./
COPY auth-module ./auth-module

RUN chmod +x ./gradlew
RUN ./gradlew :auth-module:bootJar --no-daemon --stacktrace --info

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

COPY --from=build /app/auth-module/build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]
