server:
  port: ${PORT:8084}

spring:
  application:
    name: preview-service

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: INFO
    com.pebble.preview: DEBUG
